### ISSUE TITLE
Bug: The frontend unit tests step in Travis does not run all the frontend unit tests

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3779]
## Description and expectations

The Travis script does not run unit tests of several apps, including those of `frontend_app_share_folder_advanced` and `frontend_app_collaborative_document_edition`:

```
    - stage: frontend
      name: Frontend unit tests
      install:
        - ./install_frontend_dependencies.sh
        - ./build_full_frontend.sh
      env:
        - TRAVIS_NODE_VERSION="10"
      script:
        - cd $TRAVIS_BUILD_DIR/frontend_lib
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_html-document
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_file
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_thread
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_folder_advanced
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_workspace
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_workspace_advanced
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_agenda
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_admin_workspace_user
        - yarn run test
        - cd $TRAVIS_BUILD_DIR/frontend_app_gallery
        - yarn run test
        - cd $TRAVIS_BUILD_DIR
```

To do:
 - [x] use `./run_frontend_unit_test.sh', that runs all the unit tests and fails if one of the app has failing tests

Note: all tests are green locally, so no tests are to fix.
