### ISSUE TITLE
Bug: The scroll in the custom login page doesn't go to the bottom

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#4535]
## Description and expectations

When a scroll is required on the custom login page, we cannot scroll to the bottom. It lacks 61px of scroll.

### How to reproduce

- Have a custom login page with some html code that takes more than a full height page. This is to generate a scroll in the left pane
- try to scroll to the bottom
- you can't reach it

________________________________________________

## Diagnostic

the div `.loginpage__welcome` has a `height: 100vh` but it is bellow the header which has a height of 61px.
The fix is:
``` css
.loginpage__welcome {
  max-height: calc(100vh - 61px); /* INFO - some_dev - some_date - 61 is the header's height */
  background-repeat: no-repeat;
}
```
Note that the background-repeat is to avoid a small background repetition at the bottom.
