### ISSUE TITLE
Feat: allow users to disable read statuses

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4999]
## Feature description and goals

Loading read statuses are currently slow, and I don't use them. I don't use Tracim this way. As a result, they are quite "noisy" in the interface too. Some things are bold, some are not, and since they are quite meaningless to me, I'd rather not have them at all to have a more uniform interface.

I'm sure they are useful for other people, so we probably should not get rid of this feature, but we could allow the user to disable them (with a checkbox like "show unread content in bold", or something). This could be a custom user configuration used by the frontend.

## Workaround

uBlock Origin can be used to block calls to `/read_status` and `/read`. This makes Tracim way faster but this makes Tracim show a "Server unreachable" flash error message. Browser extensions to add user stylesheets can be used to make Tracim's error message not intrusive.

```
||tracim.example.org/api/users/*/read_status
||tracim.example.org/api/users/*/read
 ```
(replacing tracim.example.org by the domain name of your instance)

To make make flash messages less annoying, you can customize their style using an extension like Stylus:

```css
.flashmessage {
    position: absolute;
    bottom: 1ex;
    left: 1ex;
    padding: 0;
    margin-left: 0 !important;
    margin-top: 0 !important;
}

.flashmessage__container {
    width: auto !important;
    max-width: 800px;
}

.flashmessage__container.card {
    margin-top: 0;
}
```

Tracim v3.9, v3.10
