### ISSUE TITLE
✨ Feat: Allow Redis cluster for session management

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#6255]
### Feature description

Currently, Tracim can manage sessions using a redis database.
Expected: investigate and document how to manage a redis database cluster - cf https://redis.io/docs/management/scaling/ 

### How it works

The expected behavior is to run "as it does currently" or to adapt the way tracim is configured in order to allow multiple redis hosts / a redis cluster config for session management.

This is not required for async task processing

### Related PR

 #6262

**Comment by Millefeuille42** [comment]
redis cluster system uses shards and replicas system. For x masters redis spawns x replicas, totaling to 2x nodes for a cluster. A single server can host a master and a replica (but should not host a server and it's replica)

It is highly recommended to have at minimum 3 masters.
> Note that the minimal cluster that works as expected must contain at least three master nodes. For deployment, we strongly recommend a six-node cluster, with three masters and three replicas.

Source: https://redis.io/docs/management/scaling/#create-a-redis-cluster

The `redis-py` package natively supports redis clusters 
- `redis-py` doc: https://redis-py.readthedocs.io/en/stable/clustering.html
- redis cluster codespec: https://redis.io/docs/reference/cluster-spec/

It should not be that hard to implement redis cluster support in tracim. It also seems like `redis-py` is capable of retrieving the different nodes by itself. Meaning that the configuration could point to a single node instead of the whole cluster.

**Comment by lebouquetin** [comment]
@Millefeuille42 thanks for the investigation. Here come some information about tracim source code and redis configuration: 

```
(env) damien@christophecolomb:~/tracim$ pip show redis
Name: redis
Version: 3.5.3
Summary: Python client for Redis key-value store
Home-page: https://github.com/andymccurdy/redis-py
Author: Andy McCurdy
Author-email: ***
License: MIT
Location: /home/damien/tracim/backend/env/lib/python3.9/site-packages
Requires: 
Required-by: rq, tracim-backend
(env) damien@christophecolomb:~/tracim$ 
```

According to the documentation you point to, we are already ready for redis clustering

**Comment by Millefeuille42** [comment]
Yup, from what I understood we "just" have to change the import to `redis.cluster` instead of `redis` when cluster mode is activated. We might add a line in the `.ini` to toggle redis cluster mode

**Comment by lebouquetin** [comment]
Could you test this @Millefeuille42 . You can "only" configure a cluster with 1 node... According to `pip freeze` result, we are using pyramid_beaker for session management... which is quite a bit old...

**Comment by Millefeuille42** [comment]
@lebouquetin 

I am aware that we are using `pyramid_beaker` but did not thought of that...

I'll test this (maybe with a 2 master cluster since it will be closer to our use case). I will see the behavior when trying to communicate with nodes. Chances are that the requests will be sent to just a node and that the node will redirect the request by itself which should integrate correctly with older software.

**Comment by Millefeuille42** [comment]
@lebouquetin having a cluster returns this error on tracim

```
redis.exceptions.ResponseError: MOVED 13547 10.10.14.6:6379
```

What we could do is to code our own `redis-cluster` driver for `pyramid_beaker` or to find / code a redis proxy...

I don't think it is *that* hard (and it should exist I'm sure)

**Comment by Millefeuille42** [comment]
It works 🥳 We need to build the image though but it's not hard

**Comment by Millefeuille42** [comment]
@lebouquetin 

To sum things up:

- redis clusters needs at least 6 nodes with a recommended minimum of 3 separates machines
- tracim itself cannot interact with redis clusters due to the use of `pyramid_beaker` which doesn't support redis clusters.
- To work around the above issue, there is https://github.com/RedisLabs/redis-cluster-proxy that acts as a proxy for the redis cluster.

I have tested tracim with the following configuration:

- 6 redis node configured as a cluster
  - 3 masters
  - 3 replicas
- 1 redis proxy acting as tracim's entrypoint

And it works. We might need to consider the fact that having a single entrypoint has an impact of performance of the cluster. The proxy needs to be able to handle some load.

**Comment by Millefeuille42** [comment]
@lebouquetin

Here are the files I used for testing. They are not *good* at all, but this is enough for local testing. Feel free to ask if you have any question.

- `docker-compose.yml`
```yaml
version: "3"
services:
  redis-entry:
   image: redis:7.2.3-alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   volumes:
     - ${PWD}/redis_conf_folder:/usr/local/etc/redis
  redis-node-1:
   deploy:
   image: redis:7.2.3-alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   volumes:
     - ${PWD}/redis_conf_folder:/usr/local/etc/redis
  redis-node-2:
   deploy:
   image: redis:7.2.3-alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   volumes:
     - ${PWD}/redis_conf_folder:/usr/local/etc/redis
  redis-node-3:
   deploy:
   image: redis:7.2.3-alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   volumes:
     - ${PWD}/redis_conf_folder:/usr/local/etc/redis
  redis-node-4:
   deploy:
   image: redis:7.2.3-alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   volumes:
     - ${PWD}/redis_conf_folder:/usr/local/etc/redis
  redis-node-5:
   deploy:
   image: redis:7.2.3-alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   volumes:
     - ${PWD}/redis_conf_folder:/usr/local/etc/redis
  redis-cluster-configure:
   image: redis:7.2.3-alpine
   command: /usr/local/etc/redis/redis-cluster-create.sh
   depends_on:
     - redis-entry
     - redis-node-1
     - redis-node-2
     - redis-node-3
     - redis-node-4
     - redis-node-5
   volumes:
     - ${PWD}/redis_conf_folder:/usr/local/etc/redis
  redis-cluster-proxy:
    build: ./redis_cluster_proxy
    ports:
      - "6379:7777"
    depends_on:
      redis-cluster-configure:
        condition: service_completed_successfully
```

- `redis_conf_folder/redis.conf`
```conf
port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
```

- `redis_cluster_proxy/Dockerfile`
```dockerfile
FROM debian:buster-slim as builder

RUN apt update && apt -y upgrade && apt -y install gcc make git
RUN git clone https://github.com/RedisLabs/redis-cluster-proxy.git

WORKDIR redis-cluster-proxy
RUN make

FROM debian:buster-slim as runner
COPY --from=builder /redis-cluster-proxy/src/redis-cluster-proxy /redis-cluster-proxy
COPY --chmod=777 ./entrypoint.sh /entrypoint.sh

CMD sleep 5 && ./redis-cluster-proxy $(getent hosts redis-entry | awk '{ print $1 }'):6379
```

- `redis_conf_folder/redis-cluster-create.sh`
```sh
sleep 3

node_0_ip=$(getent hosts redis-entry | awk '{ print $1 }')
node_1_ip=$(getent hosts redis-node-1 | awk '{ print $1 }')
node_2_ip=$(getent hosts redis-node-2 | awk '{ print $1 }')
node_3_ip=$(getent hosts redis-node-3 | awk '{ print $1 }')
node_4_ip=$(getent hosts redis-node-4 | awk '{ print $1 }')
node_5_ip=$(getent hosts redis-node-5 | awk '{ print $1 }')
redis-cli --cluster create $node_0_ip:6379 $node_1_ip:6379 $node_2_ip:6379 $node_3_ip:6379 $node_4_ip:6379 $node_5_ip:6379 --cluster-replicas 1 --cluster-yes
```
